package net.vs49688.rafview.gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import net.vs49688.rafview.inibin.*;

public class DDSViewer extends JPanel {

	private Map<Integer, Value> m_DDS;
	
	public DDSViewer(ActionListener listener) {
		initComponents();

		m_LoadExternalBtn.addActionListener(listener);

		setDDS("", null);
	}

	public final synchronized void setDDS(String name, byte[] dds) {
		if(dds == null) {
			name = "";
		}
		
		m_NameLabel.setText(name);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup treatGroup = new javax.swing.ButtonGroup();
        m_LoadExternalBtn = new javax.swing.JButton();
        m_NameLabel = new javax.swing.JLabel();

        m_LoadExternalBtn.setText("Load External File");
        m_LoadExternalBtn.setActionCommand("dds->loadexternal");

        m_NameLabel.setText("<NAME GOES HERE>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addComponent(m_LoadExternalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_LoadExternalBtn)
                    .addComponent(m_NameLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m_LoadExternalBtn;
    private javax.swing.JLabel m_NameLabel;
    // End of variables declaration//GEN-END:variables
}
